In [4]:
import numpy as np

In [3]:
## numpy array

In [5]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [6]:
## create numpy array from scratch

In [10]:
np.zeros([2, 4], dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [12]:
np.full((3, 5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [13]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
## random

In [16]:
np.random.random((4,4))

array([[0.77986285, 0.98160562, 0.95391575, 0.19778265],
       [0.86840558, 0.66297362, 0.22631848, 0.51716256],
       [0.90659429, 0.66665702, 0.27312113, 0.35217177],
       [0.52299093, 0.45878803, 0.20008535, 0.39453725]])

In [17]:
## array indexing and slicing

In [18]:
x1 = np.random.randint(20, size=6)

In [19]:
x1

array([ 9, 16, 14,  6, 10,  4])

In [22]:
x1[4], x1[0], x1[-1]

(10, 9, 4)

In [23]:
## multi dimensional array

In [24]:
x2 = np.random.randint(10, size=(3,4))

In [25]:
x2

array([[8, 6, 2, 8],
       [8, 8, 4, 9],
       [7, 7, 6, 4]])

In [26]:
x2[1, 2]

4

In [28]:
x1[0:3]

array([ 9, 16, 14])

In [29]:
x1[::2]

array([ 9, 14, 10])

In [30]:
x2

array([[8, 6, 2, 8],
       [8, 8, 4, 9],
       [7, 7, 6, 4]])

In [31]:
## two rows, three columns
x2[:2, :3]

array([[8, 6, 2],
       [8, 8, 4]])

In [33]:
x2[:, :2]

array([[8, 6],
       [8, 8],
       [7, 7]])

In [34]:
## reshaping of array & transpose

In [35]:
grip = np.arange(1, 10)
grip.shape

(9,)

In [36]:
grip.reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
x = np.array([1, 2, 3])

In [38]:
x.shape

(3,)

In [39]:
x.reshape((1, 3)).shape

(1, 3)

In [42]:
x = np.array([[1.,2.],[3.,4.]])

In [43]:
x

array([[1., 2.],
       [3., 4.]])

In [44]:
x.T

array([[1., 3.],
       [2., 4.]])

In [45]:
## array concatenation and splitting

In [46]:
x = np.array([1,2,3])

In [47]:
y = np.array([3,2,1])

In [49]:
np.concatenate((x, y))

array([1, 2, 3, 3, 2, 1])

In [50]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

In [51]:
grip

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.concatenate((grid, grid)) # axios = 0 default

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [54]:
np.concatenate((grid, grid), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [55]:
#vstack
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])

In [56]:
np.vstack((x, grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [59]:
# horizontally stack the arrays: hstack
y = np.array([[99], [99]])
np.hstack((y, grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

In [60]:
## splitting of arrays

In [61]:
x = np.array([1, 2, 3, 99, 69, 3, 2, 1])

In [62]:
x

array([ 1,  2,  3, 99, 69,  3,  2,  1])

In [64]:
x1, x2, x3 = np.split(x, [3, 5])


In [65]:
x1

array([1, 2, 3])

In [66]:
x2

array([99, 69])

In [67]:
x3

array([3, 2, 1])

In [68]:
## broadcasting and vectorized operations

In [69]:
a = np.arange(3)

In [70]:
a

array([0, 1, 2])

In [71]:
a + 5 #broadcasting

array([5, 6, 7])

In [72]:
b = np.ones((3, 3))

In [73]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [74]:
a.shape, b.shape

((3,), (3, 3))

In [75]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [76]:
c = np.arange(3).reshape((3, 1))

In [77]:
c

array([[0],
       [1],
       [2]])

In [78]:
c + a

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [79]:
## manipulating & comparing arrays

In [81]:
list_number = [1, 2, 3]

In [82]:
ll = np.array(list_number)

In [83]:
ll

array([1, 2, 3])

In [85]:
sum(ll) ##python sum

6

In [86]:
np.sum(ll) #numpy sum

6

In [87]:
# create massive numpy array

In [89]:
m_array = np.random.random(10000)
m_array[:5]
m_array.size

10000

In [90]:
%timeit sum(m_array)

405 µs ± 12.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [91]:
%timeit np.sum(m_array)

2.94 µs ± 14.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [92]:
np.mean(m_array)

0.4988629710956892

In [93]:
np.max(m_array)

0.999953274322156

In [94]:
np.min(m_array)

0.00011170937510562862

In [95]:
# standard deviation (Độ lệch chuẩn) and Variance (Phương sai)

In [96]:
dog_h = [600, 470, 170, 430, 300]
np_h = np.array(dog_h)
np.std(np_h)

147.32277488562318

In [97]:
np.var(np_h)

21704.0

In [98]:
np.sqrt(np.var(np_h))

147.32277488562318

In [99]:
# sorting arrays

In [100]:
x = np.array([2, 1, 3, 4, 5])

In [101]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [103]:
# return index sorted
np.argsort(x)

array([1, 0, 2, 3, 4])

In [104]:
## linear algebra

In [105]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [106]:
b = np.array([[6, 5], [4, 3], [2, 1]])

In [107]:
a.dot(b)

array([[20, 14],
       [56, 41],
       [92, 68]])